name: All CI steps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Start containers
      run: docker-compose up -d --build

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Prepare filesystem for integration test
      run: |
        sudo chown -R $(docker-compose exec -T php id -u) ./tests/Integration/var/

    - name: Run integration tests
      run: docker-compose exec -T php vendor/bin/phpunit -c tests/phpunit.xml --testsuite integration --do-not-cache-result

    - name: Run unit tests
      run: docker-compose exec -T php vendor/bin/phpunit -c tests/phpunit.xml --testsuite unit --do-not-cache-result

    - name: Stop containers
      if: always()
      run: docker-compose down
